title: Nighthawk-Pages
description: "August 2023 to June 2024"
owner_name: Chrissie Zhou
github_username: Chrissiez
github_repo: "CoolGame-Pages"
baseurl: "/CoolGame-Pages"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/Chrissiez"}

plugins:
- jekyll-remote-theme
future: true
